### ISSUE TITLE
Set the number of candles that are displayed default

### ISSUE THREAD

**Issue by mohanc4547** [C451/trading-vue-demo#1]
Set the number of candles that are displayed default on screen load

Setting the ChartConfig, 
halved GRIDX to 50 
DEFAULT_LEN to 100 
but neither does not seem to work 

used npm run dev after each change as well 
Could you please help me with that ?

**Comment by C451** [comment]
Oh, missed this one. Are you using this repo or the main one? (https://github.com/C451/trading-vue-js)

To set a new config you need to pass it to TradingVue component: 

```html
<trading-vue :chart-config="{GRIDX:50,DEFAULT_LEN:100}">
</trading-vue>
```

**Comment by mohanc4547** [comment]
Hey you have done it, I have been playing with the older tradingvue that
does not have constants.js affecting the chatt, rather I was forced to go
inside dist/tradingvuejs properly. I suppose the new version( .10 version)
handles properly

Defaultlen is the parameter that I modified

Can you upload the grin js project properly( in a working condition)
please, I am new to Vue js, I don't see the grin in a working condition
with the current project(For overlay example)

Can you make the volume overlay added offchart to contain alternateing
colors.

I just need an example and I can extrapolate from there onwards

**Comment by C451** [comment]
Ahh, you mean this grin https://gist.github.com/C451/6d8ea8d603e3faadd801b4b3f2e7a57d ?

> Can you make the volume overlay added offchart to contain alternateing
colors.

Already done, check this https://github.com/C451/trading-vue-js/blob/master/test/tests/ChartTypes.vue

`npm run test` in the main repo

**Comment by C451** [comment]
Also, have you checked https://github.com/C451/trading-vue-101 ? Will be a great starting point.

**Comment by mohanc4547** [comment]
Yup , scoured all of it :) , splendid piece of work, on the lib as well as
the examples.

**Comment by C451** [comment]
Thanks, but some people say they want more examples and docs :)

**Comment by mohanc4547** [comment]
Cool Buddy

My mistake I don't know the ABCs of the libraries, but try to tweak stuff
that is there through simple Js modifications

Today I learned I need to go to test folders to scour for the sample
datasets , yeah volume chart settings and examples are the ones I needed :)

Add-on if you have time: In the possible list of overlays you can have a
text related overlay also, to display a message that occupies say the whole
of the offchart

Currently I am using the ema  "name" to display my message while I render
the chart. Wherein during data creation I use type = ema , name = "my
message" and push data.json on to the directory and the chart gets
refreshed,
I use c# to render my data into the data folder, whereby the page gets
refreshed

**Comment by C451** [comment]
Its ok, 

It's not a problem for me to add a new overlay, the real problem is time. This lib is a small part of a larger TBA project, smth like 1/10th :)

I was hoping people would be able to make their own overlays, which is fairly easy if you know Vue. Unfortunately, this is not the case for now. Maybe better docs can improve the situation.
